#![cfg(test)]

//! Randomized / fuzz testing for the vault's principal-retention (zero-loss)
//! guarantee under yield volatility.
//!
//! The hand-written scenarios in `test.rs` only probe fixed paths; this module
//! drives ≥1,000 randomized actions per three fixed seeds — skewed deposits
//! (including dust amounts that truncate to zero interest in the mock pool),
//! partial and full exits, draws after random ledger gaps, and rate swings —
//! and asserts the five invariants after *every* action:
//!
//!   1. `total_deposits == Σ user_balance`
//!   2. every user balance ≥ 0
//!   3. the vault's own token balance is always 0 (principal lives in the pool)
//!   4. pool token balance ≥ `total_deposits` (principal never lost)
//!   5. every user can withdraw their full recorded balance (exercised on a
//!      sampled subset)
//!
//! ## Reproducibility
//!
//! Actions are generated by a small fixed-seed LCG (no external crate needed;
//! the workspace pins `soroban-sdk = "=27.0.5"` and `proptest` would add
//! significant compile time for little extra value here). On failure the panic
//! message carries the full seed, the action index, and a replayable log of
//! every action taken so far.

extern crate std;

use std::string::String;

use soroban_sdk::{
    Address, Env, Vec,
    testutils::{Address as _, Ledger as _},
    token,
};

use crate::test::{MockYieldPool, MockYieldPoolClient};
use crate::{AquaVault, AquaVaultClient};

const N_USERS: usize = 8;
const DRAW_INTERVAL_SECS: u64 = 86_400;
const ACTIONS_PER_SEED: u32 = 334;
/// Every Nth step, re-read all user balances on-chain (bounds runtime).
const FULL_VERIFY_EVERY: u32 = 5;
/// Every Nth step, exercise full withdrawals on a sampled user subset.
const EXERCISE_EVERY: u32 = 20;
const SEEDS: [u64; 3] = [
    0x9E37_79B9_7F4A_7C15,
    0xBF58_476D_1CE4_E5B9,
    0x94D0_49BB_1331_11EB,
];

/// Fixed LCG (numerical recipes). Deterministic per seed.
struct Lcg(u64);

impl Lcg {
    fn next(&mut self) -> u64 {
        self.0 = self
            .0
            .wrapping_mul(6364136223846793005)
            .wrapping_add(1442695040888963407);
        self.0 >> 32
    }

    fn below(&mut self, bound: u64) -> u64 {
        self.next() % bound
    }
}

struct Harness {
    env: Env,
    vault: AquaVaultClient<'static>,
    vault_id: Address,
    token: Address,
    users: Vec<Address>,
    mock_pool: Address,
}

fn harness() -> Harness {
    let env = Env::default();
    env.mock_all_auths();
    env.cost_estimate().budget().reset_unlimited();

    let mock_pool = env.register(MockYieldPool, ());
    let sac = env.register_stellar_asset_contract_v2(mock_pool.clone());
    let token = sac.address();
    let token_admin = token::StellarAssetClient::new(&env, &token);

    let mut users: Vec<Address> = Vec::new(&env);
    for _ in 0..N_USERS {
        let user = Address::generate(&env);
        token_admin.mint(&user, &1_000_000_000_000i128);
        users.push_back(user);
    }

    MockYieldPoolClient::new(&env, &mock_pool).initialize(&token, &mock_pool);
    MockYieldPoolClient::new(&env, &mock_pool).set_rate(&1_000);

    let admin = Address::generate(&env);
    let vault_id = env.register(AquaVault, ());
    let vault = AquaVaultClient::new(&env, &vault_id);
    vault.initialize(&admin, &token, &mock_pool, &Some(DRAW_INTERVAL_SECS));

    // Every user starts with a small stake so draws can succeed early.
    for user in users.iter() {
        vault.deposit(&user, &1_000);
    }

    Harness {
        env,
        vault,
        vault_id,
        token,
        users,
        mock_pool,
    }
}

fn token_balance(h: &Harness, who: &Address) -> i128 {
    token::Client::new(&h.env, &h.token).balance(who)
}

struct Fuzzer<'a> {
    h: &'a Harness,
    balances: [i128; N_USERS],
    lcg: Lcg,
    step: u32,
    log: std::string::String,
}

impl<'a> Fuzzer<'a> {
    fn new(h: &'a Harness, seed: u64) -> Self {
        Fuzzer {
            h,
            balances: [1_000; N_USERS],
            lcg: Lcg(seed),
            step: 0,
            log: std::string::String::new(),
        }
    }

    fn ctx(&self) -> String {
        std::format!(
            "seed={:016x} step={}\naction log:\n{}",
            self.lcg.0,
            self.step,
            self.log
        )
    }

    fn record(&mut self, action: std::string::String) {
        self.step += 1;
        self.log.push_str(&action);
    }

    fn pick(&mut self) -> usize {
        (self.lcg.below(N_USERS as u64)) as usize
    }

    /// Skewed deposit amounts: dust, small, medium, and large.
    fn deposit(&mut self) {
        let user = self.pick();
        let amt: i128 = match self.lcg.below(4) {
            0 => (self.lcg.below(10) + 1) as i128, // dust (1..=10)
            1 => (self.lcg.below(100) + 1) as i128,
            2 => (self.lcg.below(1_000) + 1) as i128,
            _ => (self.lcg.below(10_000) + 1) as i128,
        };
        match self
            .h
            .vault
            .try_deposit(&self.h.users.get(user as u32).unwrap(), &amt)
        {
            Ok(Ok(new_bal)) => {
                self.balances[user] += amt;
                assert_eq!(
                    new_bal,
                    self.balances[user],
                    "deposit return value drifted\n{}",
                    self.ctx()
                );
                self.record(std::format!("deposit u{user} amt={amt}\n"));
            }
            Err(Ok(_)) => self.record(std::format!("deposit u{user} amt={amt} rejected\n")),
            other => self.fail(&std::format!("unexpected deposit result: {other:?}")),
        }
    }

    /// Partial or full withdraw, occasionally over-withdrawing on purpose.
    fn withdraw(&mut self) {
        let user = self.pick();
        let bal = self.balances[user];
        let amt: i128 = if bal == 0 {
            (self.lcg.below(100) + 1) as i128 // try to withdraw from an empty account
        } else if self.lcg.below(2) == 0 {
            bal // full exit
        } else if self.lcg.below(20) == 0 {
            bal + (self.lcg.below(500) + 1) as i128 // over-withdraw
        } else {
            (self.lcg.below((bal as u64).max(1)) + 1) as i128 // partial
        };
        match self
            .h
            .vault
            .try_withdraw(&self.h.users.get(user as u32).unwrap(), &amt)
        {
            Ok(Ok(new_bal)) => {
                self.balances[user] -= amt;
                assert_eq!(
                    new_bal,
                    self.balances[user],
                    "withdraw return value drifted\n{}",
                    self.ctx()
                );
                self.record(std::format!("withdraw u{user} amt={amt}\n"));
            }
            Err(Ok(_)) => self.record(std::format!("withdraw u{user} amt={amt} rejected\n")),
            other => self.fail(&std::format!("unexpected withdraw result: {other:?}")),
        }
    }

    /// Advance the ledger by a random gap and try a draw (may hit TooEarly /
    /// NoYieldToAward / NoDepositors, all legitimate outcomes).
    fn draw(&mut self) {
        let gap = 1 + self.lcg.below(2 * DRAW_INTERVAL_SECS);
        self.h
            .env
            .ledger()
            .set_timestamp(self.h.env.ledger().timestamp() + gap);
        match self.h.vault.try_execute_prize_draw() {
            Ok(Ok(_)) => self.record(std::format!("draw gap={gap}\n")),
            Err(Ok(_)) => self.record(std::format!("draw gap={gap} rejected\n")),
            other => self.fail(&std::format!("unexpected draw result: {other:?}")),
        }
    }

    /// Swing the pool's annual rate (0% through 1000%).
    fn set_rate(&mut self) {
        static RATES: [u64; 6] = [0, 0, 100, 1_000, 10_000, 100_000];
        let rate = RATES[(self.lcg.below(RATES.len() as u64)) as usize];
        match MockYieldPoolClient::new(&self.h.env, &self.h.mock_pool).try_set_rate(&rate) {
            Ok(Ok(_)) => self.record(std::format!("set_rate {rate}bps\n")),
            other => self.fail(&std::format!("unexpected set_rate result: {other:?}")),
        }
    }

    /// Let time pass without a draw (exercises accrual without distribution).
    fn advance_only(&mut self) {
        let gap = 1 + self.lcg.below(DRAW_INTERVAL_SECS);
        self.h
            .env
            .ledger()
            .set_timestamp(self.h.env.ledger().timestamp() + gap);
        self.record(std::format!("advance gap={gap}\n"));
    }

    /// On-chain verification of invariants (1)–(4). The per-user balance mirror
    /// is cross-checked against the value each successful deposit/withdraw
    /// returned from the contract, and the full 8-user read is done on the
    /// `full` cadence (every `FULL_VERIFY_EVERY` steps) to bound runtime while
    /// still detecting any storage drift.
    fn verify(&self, full: bool) {
        let stats = self.h.vault.get_vault_stats();
        let sum: i128 = self.balances.iter().sum();

        // (1) total_deposits == Σ user_balance
        assert_eq!(
            stats.total_deposits,
            sum,
            "invariant 1 violated\n{}",
            self.ctx()
        );

        if full {
            // (2) every user balance ≥ 0 and matches the recorded balance.
            for (i, user) in self.h.users.iter().enumerate() {
                let onchain = self.h.vault.get_user_balance(&user);
                assert!(onchain >= 0, "invariant 2 violated\n{}", self.ctx());
                assert_eq!(
                    onchain,
                    self.balances[i],
                    "balance mirror drift\n{}",
                    self.ctx()
                );
            }
        }

        // (3) vault never holds the deposit token.
        assert_eq!(
            token_balance(self.h, &self.h.vault_id),
            0,
            "invariant 3 violated\n{}",
            self.ctx()
        );

        // (4) pool covers all principal.
        let pool = token_balance(self.h, &self.h.mock_pool);
        assert!(
            pool >= stats.total_deposits,
            "invariant 4 violated\n{}",
            self.ctx()
        );
    }

    /// (5) Exercise full withdrawals on a sampled subset: pull a user's full
    /// recorded balance and put it straight back.
    fn exercise_withdrawals(&mut self) {
        for _ in 0..2 {
            let user = self.pick();
            let bal = self.balances[user];
            if bal == 0 {
                continue;
            }
            match self
                .h
                .vault
                .try_withdraw(&self.h.users.get(user as u32).unwrap(), &bal)
            {
                Ok(Ok(_)) => {
                    self.balances[user] = 0;
                    match self
                        .h
                        .vault
                        .try_deposit(&self.h.users.get(user as u32).unwrap(), &bal)
                    {
                        Ok(Ok(_)) => {
                            self.balances[user] = bal;
                            self.record(std::format!("exercise full-withdraw u{user} amt={bal}\n"));
                        }
                        other => {
                            self.fail(&std::format!("unexpected re-deposit result: {other:?}"))
                        }
                    }
                }
                other => self.fail(&std::format!(
                    "full withdrawal of u{user} failed: {other:?}"
                )),
            }
        }
    }

    fn fail(&self, msg: &str) -> ! {
        panic!("{}\n{}", msg, self.ctx());
    }
}

#[test]
fn test_fuzz_principal_retention_across_seeds() {
    for seed in SEEDS {
        let h = harness();
        let mut f = Fuzzer::new(&h, seed);
        for _ in 0..ACTIONS_PER_SEED {
            match f.lcg.below(100) {
                0..=39 => f.deposit(),
                40..=69 => f.withdraw(),
                70..=84 => f.draw(),
                85..=94 => f.set_rate(),
                _ => f.advance_only(),
            }
            f.verify(f.step % FULL_VERIFY_EVERY == 0);
            if f.step % EXERCISE_EVERY == 0 {
                f.exercise_withdrawals();
            }
        }
        // After every seed: flush any accrued-but-undrawn yield with one final
        // draw (interval elapses first), then everyone exits with their full
        // principal.
        let final_total: i128 = f.balances.iter().sum();
        if final_total > 0 {
            h.env
                .ledger()
                .set_timestamp(h.env.ledger().timestamp() + DRAW_INTERVAL_SECS);
            match h.vault.try_execute_prize_draw() {
                Ok(Ok(_)) | Err(Ok(_)) => {} // yield may be exactly 0 → NoYieldToAward
                other => f.fail(&std::format!("final flush draw failed: {other:?}")),
            }
        }
        for (i, user) in h.users.iter().enumerate() {
            let bal = f.balances[i];
            if bal > 0 {
                let res = h.vault.try_withdraw(&user, &bal);
                if !matches!(res, Ok(Ok(_))) {
                    f.fail(&std::format!("final full exit of u{i} failed: {res:?}"));
                }
            }
        }
        let stats = h.vault.get_vault_stats();
        assert_eq!(
            stats.total_deposits, 0,
            "vault not drained after seed {seed:016x}"
        );
        assert_eq!(
            stats.participants.len(),
            0,
            "depositors not unregistered after seed {seed:016x}"
        );
        assert_eq!(
            token_balance(&h, &h.vault_id),
            0,
            "vault still holds tokens after seed {seed:016x}"
        );
        // The pool drains only if there was principal to distribute yield to;
        // if everyone had already exited mid-run, leftover interest is orphaned
        // (legitimately undistributable) and may remain.
        if final_total > 0 {
            assert_eq!(
                token_balance(&h, &h.mock_pool),
                0,
                "pool should drain after a flushing draw (seed {seed:016x})"
            );
        }
    }
}
